name: 🌟 Create Release

on:
    push:
        tags:
            - v*

jobs:
    build:
        uses: ./.github/workflows/call-make.yml
        with:
            create-artifact: true
            artifact-name: "z0ne_collections"

    release:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: write
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: '0'

            - name: 📥 Download Artifact
              uses: actions/download-artifact@v3
              with:
                  name: "z0ne_collections"

            - name: 💾 Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "**/*.nupkg"
